name = "FMSynth"
uuid = "fbc5c0f3-52a8-4882-83c0-0d2ababde38b"
authors = ["Simeon Schaub <simeondavidschaub99@gmail.com>"]
version = "0.1.0"

[deps]
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"

[compat]
julia = "1"
SampledSignals = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
