name = "FMSynth"
uuid = "fbc5c0f3-52a8-4882-83c0-0d2ababde38b"
authors = ["Simeon Schaub <simeondavidschaub99@gmail.com>"]
version = "0.1.0"

[deps]
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
